# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

TUTORIAL 1

In [2]:
print("Hello world !")



Hello world !


In [3]:
type(7)


int

In [4]:
len("Sabrina")


7

In [5]:
type("true"
     )

str

In [10]:
my_name = "Smriti"
age = 20
print("My name is (). I am () years old".format( my_name , age))

My name is (). I am () years old


In [1]:
10* 'str '

'str str str str str str str str str str '

In [2]:
10**2


100

In [3]:
##type function
type(10)

int

In [4]:
type(True)
type("hello")

str

In [5]:
type("hello"
     )

str

In [6]:
#STRINGS
a = 'Smriti'
type(a)

str

In [12]:
a= 10
b = 20
print(a+b) ##bodmas rule is followed
print(a*b)
print(a/b)
print(b -a)

30
200
0.5
10


In [8]:
namelo = 'Smriti'
age = 20
print("My name is {}. I am old as {}".format(namelo,age))

My name is Smriti. I am old as 20


TUTORIAL 2

In [36]:
print(True, False)

True False


In [44]:
type(False)


bool

In [17]:
my_str = 'Smriti'


print(my_str.isalnum()) #if all char numbers DOUBT
print(my_str.isalpha()) #if all char are alphabetic
print(my_str.isdigit()) #if the starting letter is written in capital
print(my_str.isupper()) #in upper case #DOUBT
print(my_str.islower()) #in lower?
print(my_str.endswith('i'))
print(my_str.startswith('p'))

True
True
False
False
False
True
False


In [100]:
#boolean and logical operations
True or False


True

In [2]:


False or False

False

In [3]:
True and False


False

In [4]:
True and True


True

In [50]:
my_str = 'Smriti'
example = 'Hello world'
my_str.isalpha() or example.isnum()



True

AttributeError: 'str' object has no attribute 'isaplha'

In [13]:
#LISTS
type([])


list

In [14]:
example  = []
type(example)

list

In [15]:
lst = [ 'lily', 'tulip', 1,2]
type(lst)

list

In [18]:
lst = list()
type(lst)

list

In [19]:

lst =lst = [ 'lily', 'tulip', 1,2]
lst[:]

['lily', 'tulip', 1, 2]

In [45]:
lst = [ 'lily', 'tulip', 1,2, 'a','sabrina']
lst.append("taylor") #Append


In [34]:
lst = [ 'lily', 'tulip', 1,2, 'a','sabrina']
type(lst)

list

In [35]:
lst = [ 'lily', 'tulip', 1,2]
lst.insert( 2, 'lily collins') #inserting element at certain position


In [38]:
lst = [ 'lily', 'tulip', 1,2]
len(lst)

4

In [39]:
lst = [ 'lily', 'tulip', 1,2]
lst[1]

'tulip'

In [43]:
lst = [ 'lily', 'tulip', 1,2]
lst.append("taylor")



In [48]:
lst = [ 'lily', 'tulip', 1,2]
lst.append("Taylor")

In [49]:
lst = [ 'lily', 'tulip', 1,2]
lst.append("Taylor")

In [51]:
#indexing in a list
lst = [ 'lily', 'tulip', 1,2,4,5]
lst[1:4]

['tulip', 1, 2]

In [54]:
lst = [ 'lily', 'tulip', 1,2,5,9]
lst[4]


5

In [60]:

lst = [ 'lily', 'tulip', 1,2,5,9]
lst.extend([ 8,3])

In [61]:
lst = [ 'lily', 'tulip', 1,2,5,9]
lst.extend([32,44])

In [62]:
lst = [ 'lily', 'tulip','lily',  1,2,5,9,'lily']
#indexing( element , starting index , ending index)
lst.index('lily' , 0,3)

0

In [99]:
lst = [ 1,2,5,9]
lst.append(1)

In [75]:
#VARIOUS OPERATION THAT WE CAN PERFORM ON THE LIST
lst = [ 'lily', 'tulip', 1,2,5,9]
lst.pop()#popmethod

9

In [76]:
lst = [ 'lily', 'tulip', 1,2,5,9]
lst.pop(4)

5

In [6]:
lst = [ 'lily', 'tulip', 1,2,5,9,10,9,1]
lst.pop()

1

In [87]:
nums=  [ 1,2,5,9]
sum(nums)#addition



17

In [89]:
#count(claculates total occurrence of a given element of a list
lst = [ 'lily', 'tulip', 1,2,5,9,'lily']
lst.count('lily')

2

In [90]:
#Len calculates the length og the list
lst = [ 'lily', 'tulip', 1,2,5,9]
len(lst)

6

In [94]:
#max and min in a list
lst = [  1,2,5,9]
max(lst)



1

In [29]:
lst = [  1,2,5,9]
min(lst)

1

In [98]:
#index: returns the index of first occurrence . start and end index are not necessary
lst = [ 5,7,4,2,3,2, 1,2,5,9]
lst.index(1, 0,8)

6

TUTORIAL - 3

In [ ]:
# set has
#unordered data, that is iterable, mutable and has NO duplicate elements.
#set doesnt support indexing.


In [102]:
myset = {"bat", "aqua", "super","spider"}
print(myset)
type(myset)

{'super', 'spider', 'bat', 'aqua'}


set

In [105]:
#Inbuilt functions in set
#addition of sets
myset = {"bat", "aqua", "super","spider"}
myset.add("hulk")
print(myset)


{'hulk', 'spider', 'super', 'bat', 'aqua'}


In [106]:

#Difference of sets
myset = {"bat", "aqua", "super","spider"}
ourset = {"bat", "aqua", "super","spider", "hulk"}
ourset.difference(myset)

{'hulk'}

In [107]:
ourset #ouset is not updated yet. to fix it , we use update fucntion


{'aqua', 'bat', 'hulk', 'spider', 'super'}

In [110]:
myset = {"bat", "aqua", "super","spider"}
ourset = {"bat", "aqua", "super","spider", "hulk"}
ourset.difference_update(myset)

In [112]:
myset = {"bat", "aqua", "super","spider"}
ourset = {"bat", "aqua", "super","spider", "hulk"}
ourset.difference_update(myset)
print(ourset)

{'hulk'}


In [113]:
ourset#the ourset is updated now after using difference update fucntion.


{'hulk'}

In [114]:
myset = {"bat", "aqua", "super","spider"}
ourset = {"bat", "aqua", "super","spider", "hulk"}
ourset.intersection(myset)

{'aqua', 'bat', 'spider', 'super'}

In [115]:
ourset

{'aqua', 'bat', 'hulk', 'spider', 'super'}

In [117]:
myset = {"bat", "aqua", "super","spider"}
ourset = {"bat", "aqua", "super","spider", "hulk"}
ourset.intersection_update(myset) #update command updates the new list
ourset

{'aqua', 'bat', 'spider', 'super'}

In [119]:
#DICTIONARIES

type(dict()) #creating an empty dictionary

dict

In [120]:
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
type(mydict)


dict

In [126]:
#printing all the items of the the dictionary
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
for x in mydict.items():
    print(x)

('carA', 'Audi')
('carB', 'Benz')
('carC', 'Jeep')


In [136]:
#Indexing in dictionaries
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
mydict['carA']

'Audi'

In [137]:
#printing the KKEY
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
for x in mydict:
    print(x)

carA
carB
carC


In [32]:
#Printing the Values
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
for x in mydict.values():
    print(x)

Audi
Benz
Jeep


In [141]:
#replacing items in the dictionary
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
mydict['carC'] = 'limo'
mydict

{'carA': 'Audi', 'carB': 'Benz', 'carC': 'limo'}

In [142]:
#Adding items in the dictionary
mydict = { "carA" : "Audi" , "carB" : "Benz" , "carC" : "BMW" , "carC" : "Jeep" }
mydict['carD'] = ' cycle'
mydict

{'carA': 'Audi', 'carB': 'Benz', 'carC': 'Jeep', 'carD': ' cycle'}

In [143]:
#NESTED DICTIONARIES
taylor = {'speak now' : 'emma'}
sabrina = {'manfriend' : 'manchild'}
gracie = {'story' : 'us'}
pop = {'singer1': taylor, 'singer2': sabrina, 'singer3': gracie}
print(pop)

{'singer1': 'taylor', 'singer2': 'sabrina', 'singer3': 'gracie'}


In [145]:
#indexing
print(pop['singer2'])

sabrina


In [149]:

taylor = {'speak now': 'emma'}
sabrina = {'manfriend': 'manchild'}
gracie = {'story': 'us'}
pop = {'singer1': taylor, 'singer2': sabrina, 'singer3': gracie}
print(pop['singer1']['speak now'])

emma


In [ ]:
#TUPLES


In [151]:
#tuple data cant be altered. element assignment is not allowed.
mytuple = ()
print(mytuple)

()


In [153]:
mytup = ("france", "germany", "iceland")
mytup[0]

'france'

In [157]:
mytup = ("france", "germany", "iceland")#tuple entirely can be updated but not single data can be altered.
mytup=('nigeria', 'andaman')
print(mytup)

('nigeria', 'andaman')


In [158]:
#inbuilt functions in tuples
mytup = ("france", "germany", "iceland")
mytup.count('france')

1

In [159]:
#indexing
mytup = ("france", "germany", "iceland")
mytup.index('iceland')

2

TUTORIAL 4


In [1]:
import numpy as np


In [5]:
lst = [ 1,2,3,4,5]
arr = np.array(lst)

In [3]:
type(arr)


numpy.ndarray

In [7]:
arr


array([1, 2, 3, 4, 5])

In [8]:
arr.shape


(5,)

In [9]:
arr.reshape()



TypeError: reshape() takes exactly 1 argument (0 given)

In [10]:
#multinestedarray
lst1 = [ 1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]

arr = np.array([lst1,lst2,lst3])


In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [12]:
arr.shape #checking the shape of the array


(3, 5)

In [13]:
arr.reshape(5,3)
#reshaping the array

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [14]:
#dont give impossible combination
arr.reshape(2,3
            )

ValueError: cannot reshape array of size 15 into shape (2,3)

In [17]:
#INDEXING

#accessing the array of elements
 lst1 = [ 1,2,3,4,5]
 arr



IndentationError: unexpected indent (1745437840.py, line 4)

In [6]:
arr


NameError: name 'arr' is not defined

In [22]:
lstlst = [1,2,3,4,5]
arr = np.array(lstlst)


In [23]:
arr


array([1, 2, 3, 4, 5])

In [25]:
arr[1:]

array([2, 3, 4, 5])

In [26]:
arr[2]

np.int64(3)

In [ ]:
#accessing the array element

In [31]:
lst2 = [1,2,3,4,5,6,7,8,9]
arr= np.array(lst2)
